package com.vegastar.sipapp.utils.constant

object StringConstant {
    const val FORMAT_TOKEN = "Bearer %s"
    const val FORMAT_COLON = "%s: %s"
    const val FORMAT_DASH = "%s - %s"
    const val FORMAT_SUFFIX_VIETNAM_PRICE = "%sđ"
    const val FORMAT_SERVER_DATE = "yyyy-MM-dd"
    const val FORMAT_DISPLAY_DATE = "dd/MM/yyyy"
    const val FORMAT_DISPLAY_ONLY_YEAR = "yyyy"
    const val FORMAT_DISPLAY_DATE_DAY_NAME = "EEEE, dd/MM/yyyy"
    const val FORMAT_DISPLAY_DATETIME = "dd/MM/yyyy HH:mm:ss"
    const val FORMAT_HOUR_MINUTE = "HH:mm"
    const val FORMAT_HOUR_MINUTE_SECOND = "HH:mm:ss"
    const val STATUS_PENDING = "PENDING"
    const val STATUS_INPROGRESS = "IN_PROGRESS"
    const val STATUS_COMPLETED = "COMPLETED"
    const val STATUS_CANCELLED = "CANCELLED"
    const val STATUS_UNPAID = "UNPAID"
    const val ORDER_TYPE = "APPT"
    const val KEY_COMMON_HOTLINE = "APP_HOTLINE"
    const val KEY_COMMON_BANK_NUMBER = "BANK_NUMBER"
    const val KEY_COMMON_BANK_NAME = "BANK_NAME"
    const val KEY_COMMON_BANK_RECEIVER = "BANK_RECEIVER"
    const val FORMAT_GOOGLE_MAP_DIRECTION = "http://maps.google.com/maps?saddr=%s,%s&daddr=%s,%s"
    const val PREFIX_BP_SYS = "BP_SYS"
    const val PREFIX_BP_DIAS = "BP_DIAS"
    const val PREFIX_SPO2 = "SPO2"
    const val PREFIX_TEMP = "TEMP"
    const val PREFIX_HB = "HB"
    const val PREFIX_BSS = "BSs"
    const val PREFIX_HBA1C = "BS_HbA1c"
    const val PREFIX_MMOL = "BS_mmolL"
    const val PREFIX_HEIGHT = "input_height"
    const val PREFIX_WEIGHT = "input_weight"
}